server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
  }

  location = /index.html {
    add_header Cache-Control "no-store" always;
  }

  location / {
    add_header Cache-Control "no-store" always;
    try_files $uri $uri/ /index.html;
  }
}
